### ISSUE TITLE
How to obtain the proxy model

### ISSUE THREAD

**Issue by fahos** [sjoshi804/sas-data-efficient-contrastive-learning#1]
Hi, thank you for sharing the source code.
Could you please tell me where I can find the proxy model "cifar100-proxy-encoder.pt" in the sample usage?

**Comment by sjoshi804** [comment]
You can use the code in simclr.py to train a proxy model using the full data. 
As mentioned in the paper, this can be a much smaller model than the final model you want to train e.g. a ResNet18 if you want to train a ResNet50.
