### ISSUE TITLE
Not able to reproduce Res18 results on CIFAR100

### ISSUE THREAD

**Issue by IISCAditayTripathi** [sjoshi804/sas-data-efficient-contrastive-learning#3]
I am training the ResNet18 model on the CIFAR100 dataset for 400 epochs and 512 batch sizes (default parameters). I am getting a linear decoding accuracy of 62.5 %, but the numbers reported in the paper are around 66.5 %. I am observing a similar gap of 4% for the random data subsets between the results I obtained and the ones reported in the paper. I am trying to figure out what I am doing wrong. Kindly help.

**Comment by sjoshi804** [comment]
The paper uses ResNet50 for CIFAR100.

**Comment by IISCAditayTripathi** [comment]
Even with Res50, I am getting 68.77 % which seems much higher than the reported number of ~67%. What could be the reason for this discrepancy?

**Comment by IISCAditayTripathi** [comment]
What was the compute that you used while training the models? Moreover, what was the compute cost including of SAS preprocessing ?
