### ISSUE TITLE
Proxy Res50 model for CIFAR100 dataset

### ISSUE THREAD

**Issue by IISCAditayTripathi** [sjoshi804/sas-data-efficient-contrastive-learning#5]
Can you share your trained Res50 proxy model to obtain the subsets using SAS? When I generated a 20% data subset with the proxy model (fully trained Res50 using SimCLR), I obtain a linear probing accuracy of 55.13 %. However, when I used the SAS subset provided in the repository, I got 60.35% accuracy. Just so you know, the proxy Res50 model is fully trained with linear probing accuracy of 68.77%.

It would be helpful if you could share the proxy model, procedure, and setup to train the said proxy.

Thanks,
Aditay

**Comment by sjoshi804** [comment]
Hi, I did a major code-clean up before uploading this code so unfortunately my saved proxy model will not load with this code. Can you describe how which version of the subset selection you ran and I can try to validate this on my end?

**Comment by sjoshi804** [comment]
Added small proxy models.

**Comment by IISCAditayTripathi** [comment]
Hi, @sjoshi804 can you share the CIFAR100 subset that you generated using your res10 proxy? I am still facing trouble reproducing the results using the subsets produced using your updated code

**Comment by sjoshi804** [comment]
You can run the code in the notebook to recreate this subset.

**Comment by IISCAditayTripathi** [comment]
I used the code in the notebook to recreate the subset. Still it is not working.

**Comment by sjoshi804** [comment]
Can you share the accuracy you get with that subset v/s a random subset?

**Comment by IISCAditayTripathi** [comment]
I got an accuracy of 58.01 for 0.6 SAS subset using your code.

**Comment by sjoshi804** [comment]
And for the random subset?

**Comment by sjoshi804** [comment]
Are you using the exact same Contrastive Learning code for both runs? And
what is the accuracy for the full data?

I am not able to reproduce this and am able to see a gap of the reported
size.

**Comment by IISCAditayTripathi** [comment]
Can you share the subsets generated by you so that i run code on my end using that subset ?

**Comment by sjoshi804** [comment]
I have the subsets pre-generated in examples/cifar100. 

If you want the reference subsets generated by this exact code (R10, etc.), I've run the exact same notebook and shared the output here. 

[cifar100-0.6.zip](https://github.com/sjoshi804/sas-data-efficient-contrastive-learning/files/12456885/cifar100-0.6.zip)
